### ISSUE TITLE
Invite screen

### ISSUE THREAD

**Issue by kaniasty** [codeforboston/plogalong#89] opened 2019-12-09 19:27 UTC
Implement social share buttons on More>Invite

https://www.npmjs.com/package/react-share

**Comment by nlkassad** [comment] 2020-01-21 23:35
Might want to remove this from mvp

**Comment by zachjohnston** [comment] 2020-02-16 18:28
Duplicate of #15

**Comment by kaniasty** [comment] 2020-02-19 01:03
on IOS, the Share on Facebook, I get the error below.  Other buttons do nothing. 

![IMG_5478](https://user-images.githubusercontent.com/8822863/74791846-9ca0c300-5289-11ea-915c-ad1d1d410d48.PNG)

**Comment by zachjohnston** [comment] 2020-02-19 02:22
@kaniasty, I updated #15 with your screenshot, so I am re-closing this issue.

**Closed by zachjohnston** 2020-02-19 02:22 UTC
Labels: good first issue, good remote task, screen-more
